from models import SessionLocal, Exercise
from youtube_ids import YOUTUBE_IDS

exercises_data = [
    {"category": "mobility", "order": 1, "name_en": "Pelvic Tilts", "name_es": "Anteversión/Retroversión", "description_en": "Lying down, tilt your pelvis forward and backward. Important: do NOT arch your lower back. The movement must originate from the hip.", "description_es": "Acostado, movilizar la cadera hacia atrás y hacia delante. Importante NO ARQUEAR la espalda. El movimiento debe nacer desde la cadera.", "reps_or_time_en": "15 reps", "reps_or_time_es": "15 repeticiones", "tips_en": "Keep your spine neutral.", "tips_es": "Mantén la espalda neutra."},
    {"category": "mobility", "order": 2, "name_en": "Hip Circles", "name_es": "Círculos de cadera", "description_en": "In quadruped position, rotate your leg in a large circle. Focus on your hip and make the circle as wide as possible without moving your torso or arms.", "description_es": "En cuadrupedia, haz rotación de la pierna. Concéntrate en tu cadera y haz el movimiento circular lo más alto que puedas sin mover el torso o los brazos.", "reps_or_time_en": "10 per leg", "reps_or_time_es": "10 veces por pierna", "tips_en": "Connect with your hips.", "tips_es": "Conecta con tus caderas."},
    {"category": "mobility", "order": 3, "name_en": "Back Extension to the Side", "name_es": "Extensión atrás costado", "description_en": "In quadruped, extend your leg straight back and to the side as high as you can. This continues mobilizing the hip. Your arms should not move.", "description_es": "En cuadrupedia, lleva tu pierna extendida de tras al costado lo más alto que puedas. Aquí sigues movilizando la cadera. Tus brazos no deben moverse.", "reps_or_time_en": "10 per leg", "reps_or_time_es": "10 rep x pierna", "tips_en": "", "tips_es": ""},
    {"category": "mobility", "order": 4, "name_en": "Knee to Shoulder", "name_es": "Rodilla Hombro", "description_en": "Lying on your side, bring your knee as close to your ribs as possible. Exhale when you feel the tension to release the hip.", "description_es": "Acostado de lado, vas a llevar tu rodilla lo más cerca que puedas de tus costillas. Exhala cuando sientas la tensión para liberar la cadera.", "reps_or_time_en": "15 per leg", "reps_or_time_es": "15 rep x pierna", "tips_en": "", "tips_es": ""},
    {"category": "mobility", "order": 5, "name_en": "Lying Leg Raise (Battement)", "name_es": "Battement acostado", "description_en": "Lying on your back, kick your leg up as high as possible, aiming toward your face. Lower it with control.", "description_es": "Acostado mirando al techo, vas a patear hasta donde pueda la pierna, con la intención de que llegue a tu cara. Bajas controlando el peso.", "reps_or_time_en": "10 per leg x 2 sets", "reps_or_time_es": "10 rep x pierna x 2 veces", "tips_en": "", "tips_es": ""},
    {"category": "mobility", "order": 6, "name_en": "Glute Kick", "name_es": "Patada glúteo", "description_en": "In quadruped with leg extended, kick backward in a controlled manner. This works on hip extension, not power. The secret is releasing the movement.", "description_es": "En cuadrupedia con la pierna extendida, haz una patada hacia atrás. Controla el movimiento que no sea brusco. Buscas trabajar la extensión de la cadera, no la fuerza. El secreto está en liberar el movimiento.", "reps_or_time_en": "10 per leg x 2 sets", "reps_or_time_es": "10 rep x pierna x 2 veces", "tips_en": "", "tips_es": ""},
    {"category": "strength", "order": 7, "name_en": "Glute Bridge", "name_es": "Puente de Glúteos", "description_en": "Push from your heels. At the top, hold for one second and squeeze your glutes. Lower slowly and controlled, vertebra by vertebra.", "description_es": "El empuje nace desde el talón. Al llegar arriba, sostén durante un segundo y contrae los glúteos. Baja despacio y controlado, vértebra por vértebra.", "reps_or_time_en": "30 slow raises", "reps_or_time_es": "30 elevaciones lentas", "tips_en": "", "tips_es": ""},
    {"category": "strength", "order": 8, "name_en": "Single Leg Raise (Seated)", "name_es": "Elevación a una pierna", "description_en": "Sitting on the floor, raise one leg. Keep your back as straight as possible to work the hip flexor strength.", "description_es": "Sentado en el piso, levanta la pierna. La espalda debe estar lo más recta posible para trabajar la fuerza del flexor.", "reps_or_time_en": "10 per leg x 3 sets", "reps_or_time_es": "10 rep x pierna x 3 veces", "tips_en": "", "tips_es": ""},
    {"category": "strength", "order": 9, "name_en": "V-Raise (Seated)", "name_es": "Elevación en V", "description_en": "Sitting on the floor, lift both legs. Keep your back straight. Use your hands to push for support.", "description_es": "Sentado en el piso, levantar ambas piernas. Mantener la espalda recta. Ayúdate empujando con las manos.", "reps_or_time_en": "15 reps x 2 sets", "reps_or_time_es": "15 veces x 2 veces", "tips_en": "", "tips_es": ""},
    {"category": "stretches", "order": 10, "name_en": "High Hip Flexion (Chair)", "name_es": "Flexión Alta de Cadera", "description_en": "On a chair, bend forward. Keep your back straight. Push your sitting bones (ischial tuberosities) backward as you lower.", "description_es": "En una silla, flexiona hacia delante. Súper importante que la espalda esté erguida. Saca los isquios (los huesos de la cola) al bajar.", "reps_or_time_en": "20 reps x 2 sets", "reps_or_time_es": "20 veces x 2 veces", "tips_en": "", "tips_es": ""},
    {"category": "stretches", "order": 11, "name_en": "Standing Hamstring Stretch", "name_es": "Isquiotibial de Pie", "description_en": "Standing in front of a chair, bend your torso forward and relax your hamstring. If it hurts too much, bend your knee and gradually extend it.", "description_es": "Parado delante de una silla, flexionar hacia delante el torso y relajar el isquiotibial. Si te duele mucho, puedes flexionar la rodilla y poco a poco irla extendiendo.", "reps_or_time_en": "1 min per leg", "reps_or_time_es": "1 min x pierna", "tips_en": "", "tips_es": ""},
    {"category": "stretches", "order": 12, "name_en": "Deep Lunge", "name_es": "Estocada Profunda", "description_en": "From a lunge, lower your hips. Keep your knees aligned with your feet. Exhale to relax your psoas (that feeling of tension). Tip: squeeze glutes for 3 seconds and release to sink deeper.", "description_es": "Desde estocada, bajar la cadera. Que tus rodillas estén alineadas con tus pies. Exhala para relajar tu psoas (esa sensación de tensión). TIP: si deseas sentir más profundo el estiramiento, contrae los glúteos 3 segundos y suéltalos, verás que comienzas a bajar más.", "reps_or_time_en": "1 min per leg", "reps_or_time_es": "1min por pierna", "tips_en": "", "tips_es": ""},
    {"category": "stretches", "order": 13, "name_en": "Low Lunge", "name_es": "Estocada baja", "description_en": "From a lunge, bring your hands to the floor and hold. Exhale to release tension. If comfortable, lower your elbows.", "description_es": "Desde estocada, llevar manos al piso y sostener. Exhala para liberar la tensión. Si te sientes cómodo, apoya los codos.", "reps_or_time_en": "2 min per leg", "reps_or_time_es": "2 min x pierna", "tips_en": "", "tips_es": ""},
    {"category": "stretches", "order": 14, "name_en": "Pancake Stretch", "name_es": "Pancake", "description_en": "Time to move your hips! Lower down thinking about 'pushing your tail back' and chest out. Do NOT let your back round just to compensate.", "description_es": "¡Momento de mover tus caderas! Baja pensando en 'sacar tu cola' y con el pecho hacia afuera. OJO: no dejes que tu espalda se arquee si no estás bajando por compensación.", "reps_or_time_en": "1 min x 2 reps", "reps_or_time_es": "1min x 2 rep", "tips_en": "", "tips_es": ""},
]

def seed():
    db = SessionLocal()
    try:
        db.query(Exercise).delete()
        for data in exercises_data:
            name_en = data["name_en"]
            if name_en in YOUTUBE_IDS:
                data["youtube_video_id"] = YOUTUBE_IDS[name_en]
            else:
                data["youtube_video_id"] = None
            db.add(Exercise(**data))
        db.commit()
        print("✅ Database seeded with all exercises and YouTube IDs.")
    except Exception as e:
        db.rollback()
        print(f"❌ Seeding failed: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
